apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kimi-k2-model-pvc
  namespace: mpi-inference
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 600Gi
  volumeName: mpi-inference-kimi-k2-model
